# Generated by Django 5.0.7 on 2024-07-17 03:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('joint_fee', models.CharField(max_length=100)),
                ('advance_amount', models.IntegerField()),
                ('rent_amount', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number')])),
                ('join_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI')], max_length=100)),
                ('payer_phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number')])),
                ('payment_date', models.DateField()),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hosteller')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_number', models.CharField(max_length=100)),
                ('floor_number', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=100)),
                ('bed_number', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('hostel_number', 'floor_number', 'room_no', 'bed_number')},
            },
        ),
        migrations.AddField(
            model_name='hosteller',
            name='room_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.roomdetails'),
        ),
    ]
